export enum TypeNotification {
  REMINDER = 'REMINDER',
  PROMO = 'PROMO',
  SYSTEM = 'SYSTEM',
  SUBSCRIPTION = 'SUBSCRIPTION',
  ORDER_STATUS = 'ORDER_STATUS',
  NEW_INVITATION = 'NEW_INVITATION',
  LIKE = 'LIKE',
  COMMENT = 'COMMENT',
  NEW_PRODUCT = 'NEW_PRODUCT',
  FEATURED_VENDOR = 'FEATURED_VENDOR',
  TRENDING = 'TRENDING',
  STOCK_ALERT = 'STOCK_ALERT',
  WELCOME = 'WELCOME',
}

export enum NotificationChannel {
  PUSH = 'PUSH',
  IN_APP = 'IN_APP',
  SMART_CARD = 'SMART_CARD',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

