export enum TypeNotification {
  REMINDER = "REMINDER",
  PROMO = "PROMO",
  SYSTEM = "SYSTEM",
  SUBSCRIPTION = "SUBSCRIPTION",
  ORDER_STATUS = "ORDER_STATUS",
  NEW_INVITATION = "NEW_INVITATION",
}
